services:
  postgres:
    image: postgres:15
    container_name: my-postgres-db2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./chat-db-backup.sql:/docker-entrypoint-initdb.d/restore.sql
    ports:
      - "5432:5432"

  backend:
    build: ./server
    container_name: my-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      cloud_name: ${cloud_name}
      api_key: ${api_key}
      api_secret: ${api_secret}
      JWT_SECRET: ${JWT_SECRET}
      Frontend_Url: ${Frontend_Url}    
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: my-frontend
    environment:
      NEXT_PUBLIC_Backend_Url2: ${NEXT_PUBLIC_Backend_Url2}
      NEXT_PUBLIC_Frontend_Url: ${NEXT_PUBLIC_Frontend_Url}
    ports:
      - "3003:3003"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
    driver: local